name: build-pdfs


on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy to GitHub Pages
      env:
        THEME_FOLDER: ./style
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PUBLISH_TO_BRANCH: gh-pages
        BASE_URL: https://laracabrera.github.io/gcdia-bbdd/
      uses: laracabrera/marp-action@custom-theme
